### ISSUE TITLE
Declaring an extension that's not in a Github repository

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/extension_registry#113]
Once the work on [declaring the consolidated PPP extension](https://github.com/open-contracting/public-private-partnerships/issues/142) is complete, publishers will declare the PPP profile using the following URL in the `extensions` key in the release package metadata:

> http://standard.open-contracting.org/profiles/ppp/{{version}}/en/_static/consolidatedExtension/extension.json

In view of the changes to the extension registry:

1. Will it be possible to register the extension at a non-Github URL?
2. Does the PPP build need to create a ZIP of the extension?

**Comment by jpmckinney** [comment]
1. Yes, `Base URL` would be `http://standard.open-contracting.org/profiles/ppp/{{version}}/en/_static/consolidatedExtension/` (with the version filled in)
1. `Download URL` is optional (so no ZIP required)

**Comment by jpmckinney** [comment]
FYI, the new registry layout has no dependencies on GitHub.

**Comment by robredpath** [comment]
@odscjames @kindly we talked a couple of weeks ago about extensions not on GH - this is an example
