### ISSUE TITLE
Add ocds_contractsRegister_extension

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/extension_registry#119]
Can we add https://github.com/open-contracting-extensions/ocds_contractRegister_extension to the extension with category 'implementation'.

If required, we can make a 1.0 release of the extension for this after the pull request at https://github.com/open-contracting-extensions/ocds_contractRegister_extension/pull/5 is merged.

**Comment by jpmckinney** [comment]
@timgdavies Sure, can you create a PR?

**Comment by timgdavies** [comment]
Apologies I didn't spot this - though had hoped you were now on top of getting extension registry updates made - given the whole process has changed without there being training / update for the rest of the team on the new process. 

However, I've just worked through and made PR now.

**Comment by jpmckinney** [comment]
Thanks - the readme has all the documentation for anyone to use, and issues can be created or emails can be sent if anything is unclear.
