### ISSUE TITLE
Please add Extension "Contract Date created"

### ISSUE THREAD

**Issue by nenita05leyla** [open-contracting/extension_registry#124]
Hi!
Please considerer to add a new extension "DateCreated" to the registry. 
This is the link: 
[https://chilecompracl.visualstudio.com/Documentaci%C3%B3n%20OCDS/_git/ocds_contractDateCreated_extension?path=%2FREADME.md&version=GBmaster](url)
It was build to indicate the date of Contract creation because there may be a diference between the creation and the release date. 
It was validate with @yolile of OCDS HelpDesk who's helping us in the implementacion of the standard in ChileCompra. 

Thanks in advance!!

**Comment by jpmckinney** [comment]
Hi @nenita05leyla, as shared by @yolile via email, this presently satisfies the criteria for a local extension, but not for a community extension (which would be added to the registry).

As I understand, a contract is drafted, then signed, then uploaded into the system. Does `dateCreated` mean the upload date? If so, it would be clearer to name it `dateUploaded`, as 'created' can also mean the date it was drafted (i.e. the date the document was created) or the date it was signed (i.e. the date on which a legally enforceable contract was created).

**Comment by nenita05leyla** [comment]
Thanks but no is the date when the contract was created in the system and not uploaded on OCDS yet. When the contract is published (change state) then is uploaded on OCDS. 
Greetings!
