### ISSUE TITLE
Add PartiesDetails_gender extension

### ISSUE THREAD

**Issue by ivangilcruz** [open-contracting/extension_registry#126]
https://github.com/dgcpcompraspublicas/ocds_partyDetails_gender_extension

**Comment by ivangilcruz** [comment]
I have run the tests and they have passed without conflicts

**Comment by jpmckinney** [comment]
Thanks, @ivangilcruz. In the case of organizations, there is an open discussion about how to indicate facts like women-owned businesses in https://github.com/open-contracting/standard/issues/711 We should resolve that issue first.

In the case of natural persons, there is an open discussion in https://github.com/open-contracting/standard/issues/883.

We welcome your contributions to those issues. If the proposed extension ends up being the agreed model, we can re-open this issue.
