### ISSUE TITLE
Add PartiesDetails_scale extension

### ISSUE THREAD

**Issue by ivangilcruz** [open-contracting/extension_registry#127]
https://github.com/dgcpcompraspublicas/ocds_partyDetails_scale_extension

**Comment by ivangilcruz** [comment]
I have run the tests and they have passed without conflicts

**Comment by jpmckinney** [comment]
Hi @ivangilcruz, we should instead change the https://github.com/open-contracting-extensions/ocds_partyDetails_scale_extension extension, to add the 'small' and 'medium' codes.

I don't think we want a 'notclassified' code. In that case, simply leave the `scale` field blank.

Similarly, 'person' doesn't describe the scale of an organization, and a person is not an organization. I suggest using a different field to indicate this fact.

**Comment by jpmckinney** [comment]
See this issue: https://github.com/open-contracting/ocds-extensions/issues/95

Regarding 'person': if the intention was to indicate that the organization was a sole trader or a self-employed individual, then typically the existing 'micro' code is used.
