### ISSUE TITLE
GDMP Transaction Extension For OCDS

### ISSUE THREAD

**Issue by ErinClark** [open-contracting/extension_registry#130]
https://github.com/spendnetwork/gdmp-transaction-extension-for-ocds

A detailed transaction extension created by the Global Digital Marketplace from the UK Government Digital Service. The extension includes both summary transaction data and detailed information on each transaction, including unit measures, tax and item volumes.

**Purpose**
This extension was designed to support anti-corruption intiatives around the world, by allow publishers to include transaction data in any Open Contracting Initiative. Whilst transparency in contracting is a good method for preventing corruption, the Covid-19 pandemic has meant that anti-corruption initiatives have been working with limited contracting data which is insufficient to identify corruption. In this context, backwards looking Accounts Payable information, or bank statements are better suited to identifying corruption.

**Design**
This extension has been designed to allow publishers to link either Accounts Payable data or Bank Statement data into the existing OCDS contract, but in addition to provide detailed reporting on every element that is usually reported in a single invoice, for instance, the extension includes the ability to record taxes, discounts and line item fees. This granular design is critical for being able to compare the price of different items and the cost of each.

**Comment by jpmckinney** [comment]
@ErinClark The release-schema.json is not JSON Schema. Please refer to the extension template for guidance: https://github.com/open-contracting/standard_extension_template

Here is an example extension: https://github.com/open-contracting-extensions/ocds_lots_extension/

OCP and the Helpdesk have created several new resources (webinar, slide deck, etc.) to assist in the creation of extensions. You can contact the Helpdesk about these.

I am closing the issue for now, but please update it once the extension is corrected, and I will re-open it.
