### ISSUE TITLE
Add NEPCO Qualification Requirements Extension

### ISSUE THREAD

**Issue by EBRD-Open-Government-Lab-Kyiv** [open-contracting/extension_registry#136]
Please add this Extension to OCDS
https://github.com/EBRD-Collaborator/nepco_qualification_requirements

**Comment by jpmckinney** [comment]
Hi @EBRD-Collaborator, the README.md file seems to be a copy of the Requirements extension: https://github.com/open-contracting-extensions/ocds_requirements_extension

Could you update the README to (1) explain in what case(s) a publisher might want to use this extension and (2) summarize the main changes made by the extension? On a quick look, it constrains the titles of requirements, requirement groups and criteria – to promote standardized naming across publications – and it adds a value field to requirement responses.

**Comment by EBRD-Collaborator** [comment]
Hi @jpmckinney 

The Description part is added to README.md file, please take a look, if it's clear and sufficient. Thank you

**Comment by jpmckinney** [comment]
As described in #140:

> Many OCDS publications use extensions that are not shared via the extension registry. Why? First, there is no obligation to submit every extension for inclusion in the extension registry. Second, any extension that is jurisdiction-specific or system-specific is not appropriate for sharing via the extension registry.

Thank you for updating the readme. It is now clear that this extension is specific to the Jordan Public Procurement NEPCO-JONEPS System. The purpose of the extension registry is to share extensions that can be reused by other publishers. System-specific extensions – by definition – cannot be reused by others.

As such, this extension will not be added to the registry.

That said, you are free and welcome to use this extension in your own publications – like others do with their own extensions.
