### ISSUE TITLE
Add ESPD Requirements Extension

### ISSUE THREAD

**Issue by EBRD-Open-Government-Lab-Kyiv** [open-contracting/extension_registry#140]
Please add this Extension to OCDS
https://github.com/EBRD-Collaborator/espd_requirements

**Comment by jpmckinney** [comment]
I will first clarify the purpose of the extension registry. Many OCDS publications use extensions that are not shared via the extension registry. Why? First, there is no obligation to submit every extension for inclusion in the extension registry. Second, any extension that is jurisdiction-specific or system-specific is not appropriate for sharing via the extension registry.

Now, as discussed with the OCDS Helpdesk via the email thread with the subject "Re: Meeting with OCP Helpdesk", an extension for ESPD ought to match ESPD's model, which is not the same as the CCCEV model, used by the requirements extension. If the extension matches the model, it is easier for publishers to adopt.

As such, this extension is considered implementer-specific, and is not appropriate for sharing via the extension registry.

That said, you are free and welcome to use this extension in your own publications – like others do with their own extensions.
