### ISSUE TITLE
Links to community extensions in the V1.1 docs are broken

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/extension_registry#22]
Links to extension repositories and some extension documentation on the [community extensions](http://standard.open-contracting.org/1.1-dev/en/extensions/community/) page of the OCDS V1.1 documentation lead to a ```400: Invalid request``` error.

Fixing this looks like a case of updating the entries in the extension registry from links such as:

https://raw.githubusercontent.com/open-contracting/ocds_budget_projects_extension/master/

to

https://github.com/open-contracting/ocds_budget_projects_extension

Just checking that these aren't specified as "raw.githubusercontent.com" type links for a reason, before I go through and update them?

**Comment by timgdavies** [comment]
Hmm. I think the extension link needs to be to the raw version, as that is what the validator etc. uses to get the extension.json files etc.  Might need @kindly's input to make some tweaks here.

I think we could improve the display on that page by:

* Foregrounding the documentation link over the extension link;
* Displaying the extension URL to the user in the format they would need to include it in their data;

E.g.

## Multiple buyers - contract level

In some cases, a single contracting process involves multiple buyers (for example, a framework that different organisations can buy from). In these cases, the multiple buyers extension can be used to specify a distinct buyer for each contract.

Read full **documentation**

To use this extension, including the following section in your release or record package, or update the existing extensions array:

```json
{
    "extensions":["https://raw.githubusercontent.com/open-contracting/ocds_multiple_buyers_extension/master/"]
}
```




(We also need a typo fix for 'documentation' which currently is missing a t)

**Comment by edugomez** [comment]
The budget_and_project extension's `document_url`  mentioned by @duncandewhurst returns a 404 as it is missing the actual doc (eg, README.md). Anyway, I think we shouldn't show the raw version but  rather the more friendly  https://github.com/open-contracting/ocds_budget_projects_extension (which will serve the repo root page in github with the README.md file rendered).

As a side note, the fact that we use the name _extension.json_ for both files in the registry and for 'root' files in the extensions themselves introduces a bit of confusion IMO
