### ISSUE TITLE
Consider adding "extension.json" to the url for the extension 

### ISSUE THREAD

**Issue by edugomez** [open-contracting/extension_registry#38]
This was suggested by @kindly. Should the name of the file for the extension be added to the url in _registry/extension_name/extension.json_, so that instead of this:

`https://raw.githubusercontent.com/open-contracting/ocds_charges_extension/master/`

we will have this?:

`https://raw.githubusercontent.com/open-contracting/ocds_charges_extension/master/extension.json`

Notice that `https://raw.githubusercontent.com/open-contracting/ocds_charges_extension/master/` is in fact broken as no document is specified at that location.

**Comment by timgdavies** [comment]
This looks like a sensible change to me - but would it be a breaking change for what we are currently doing?

I.e. do we need to do it by 1.1 go-live on Thursday? Or are we good to make this a future change?

**Comment by edugomez** [comment]
@timgdavies I think this is rather a future change, it involves changes not only to the extensions themselves but also to cove and documentation, it might also break other things unexpectedly

**Comment by jpmckinney** [comment]
`extension.json` was added to URLs as part of #43. https://github.com/open-contracting/extension_registry/commit/10dfd1f1f5134e907634f10c98ad9611539cf1fe

Close?
