### ISSUE TITLE
Considering "certificate" as a core extension

### ISSUE THREAD

**Issue by dc-coder** [open-contracting/extension_registry#39]
In some of the PPPs or some of the "big contracts" there are different types of certificate involved:

- certificate that the bidder is qualified to participate
- certificate of completion or certificate of compliance 

I haven't seen it in a real life example, but I imagine that sometimes items used need to be certified (think ISO or UL or green energy certification) - or in case of services, people provided them need to certified professionals.

Have you looked at having certificate part of the core extensions? do you think it should be developed separately?

**Comment by timgdavies** [comment]
There has been some discussion of approvals and certification in https://github.com/open-contracting/standard/issues/403 and the work in the [Requirements Extension](https://github.com/open-contracting/ocds_requirements_extension#example-usage) can potentially be used to model a requirement that a supplier needs to be certified in a particular way.

I don't see this becoming a core extension soon, but if there is more that can be done to document implementation approaches for this based on some real data examples that would make sense. 

I would suggest moving this over to https://github.com/open-contracting/standard/issues as a discussion there unless there is a specific extension drafted to propose for inclusion in the registry.

**Comment by dc-coder** [comment]
good to know that you don't think this can be a core extension.

I am not sure about moving this to the standard issues for discussion... i feel sometimes issues need to be "worthy" - otherwise, you will become overwhelmed with issues to filter and  think through.

**Comment by timgdavies** [comment]
Good descriptions of use-cases over in the standard repo are always welcome. Useful to just surface who is interested in what - so don't worry about that.
