### ISSUE TITLE
Test that flatten-tool works with all the core extensions

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/extension_registry#41]

**Comment by Bjwebb** [comment]
I've made a start at a script for this in this GitHub gist https://gist.github.com/Bjwebb/91d409993269cdd49cb18d16c2eeb55a

I'm wondering if this should eventually live in the extension_registry repo - would mean we could set it up on travis, so we get alerted of any problems early on.

**Comment by timgdavies** [comment]
It would be great to have more testing of extensions as they are added to the registry: particularly if this can help us to know problems with an extension before merging it. 

I'll open a separate ticket with tests we might want to have.

**Comment by Bjwebb** [comment]
Thanks.

Looks like for flatten-tool, the current fatal errors are due to unresolveable JSONRefs:
* `#/definitions/RequirementResponse` in the [bid extension](https://github.com/open-contracting/ocds_bid_extension), which can be found in the [requirements extension](https://github.com/open-contracting/ocds_requirements_extension/blob/master/release-schema.json)
* `#/definitions/MilestoneReference` in the [transaction_milestones extension](https://github.com/open-contracting/ocds_transactions_relatedMilestone_extension/blob/master/release-schema.json), which can be found in the [metrics extension](https://github.com/open-contracting/ocds_metrics_extension/blob/master/release-schema.json)

`transaction_milestones` mentions this dependency in the README, but neither have it listed in a machine readable way. I don't think CoVE handles dependencies, so I think we're currently reliant on these dependencies being listed correctly in the array.

**Comment by timgdavies** [comment]
Ok. Yes - so I see https://github.com/open-contracting/ocds_bid_extension/blob/master/extension.json currently misses declaring it's dependencies.

I don't think we've clearly documented yet how dependencies should be declared. I'd been thinking this would happen with declaring the name of another extension in the registry... but realising that versioning issues could come in here - and this requires tools to lookup the extension registry to resolve a dependency link. 

Perhaps @edugomez will pick this up when working up the schemas for entry.json in the registry and extension.json in the extension template?

**Comment by Bjwebb** [comment]
There's now a pull request to put this flatten-tool based test in the extension_tester repo https://github.com/open-contracting/extension_tester/pull/2

**Comment by Bjwebb** [comment]
The flatten-tol branch of extension_tester is merged now https://github.com/open-contracting/extension_tester/pull/2, and the tests will be run nightly by travis cron.

Currently the two depencencies are hardcoded in the script. Handling dependencies properly is carried forward in https://github.com/open-contracting/standard_extension_template/issues/7
