### ISSUE TITLE
Automated tests for extensions

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/extension_registry#42]
This might also belong in https://github.com/open-contracting/extension_tester 

We've been thinking a bit about tests that could be useful, including:

(1) Does the extension provide an ```id``` property for each object it introduces (required vs. recommended?)

(2) Does the example data provided in the extension repo validate against the extension

(3) Does a schema with the extension provided still validate our sample data (we might need to create better sample data for this)

**Comment by Bjwebb** [comment]
Moving this to https://github.com/open-contracting/extension_tester/issues/3
