### ISSUE TITLE
Improve documentation of rationales for core, community and local extensions

### ISSUE THREAD

**Issue by dc-coder** [open-contracting/extension_registry#44]
If we were to stick to stick to the concept of extensions as re-usable blocks... does it make sense to try to find another technical term for describing random/additional data fields without a theme?

The suggestions i have so far instead of "OCDS extension" are:

-  "OCDS  country add-on" (which can be translated into what has been added to the OCDS from a country)
- "OCDS country module" (each data in the end needs to be displayed and processed... usually it would entail adding a specific module to an application that uses OCDS data... so we could just go with module)

Do you think it is worth it to have a brainstorming sessions on terminology for this? does this overcomplicate things? should we just stick to extensions even if they are random fields and not really re-usable?

**Comment by edugomez** [comment]
Extensions are not really thought as random fields, the idea is that some user cases may not be well covered by the existing schema, therefore the need of adding extensions to it. I think extensions are really reusable, as they try to cover identified user cases that future adopters of the schema are likely to find again. In fact, it is possible to envision a situation in which the use of an extensions becomes so common that at some point ends up being incorporated to the schema itself.

**Comment by edugomez** [comment]
@dc-coder I just realised I may have misunderstood your question, what do you mean by random and non-reusable fields?

**Comment by dc-coder** [comment]
sometimes, countries want to disclose data that is not in the standard. disclosing data outside standard is usually tackled by using extensions... like having a shareholder extension or a location extension. 

Sometimes, some people want to disclose a set of data that doesn't fit any theme or logical grouping. They are usually part of the software or the database and are less likely to become part of another OCDS implementation. 

Since this data useful to the public as disclosed data, i am wondering, should we have 2 ways to deal with it? here is what i am thinking:

- if additional data is a re-usable block, it becomes an extension
- if additional data is just some random set of data, instead of cluttering the "extensions", can we come-up with a different term or concept that reflects that? I can only think of "module" or "add-on" for now.

Is this something worth pursuing?

**Comment by timgdavies** [comment]
Ok - so - this 'random set of data' is essentially what we've been calling 'local extensions' and handling through the same extensions mechanism. 

Without an extension, they will show up in the OCDS Validator as 'additional fields'. 

We could use the term 'local add on' instead of extension if it seems a conceptual distinction is useful - but we would probably want to continue to use the same mechanism.

At the moment, the validator doesn't make any distinction between core, community and local extensions in what it feeds back - but if we assume that core and community extensions would be in the extension registry, but local not - it could report on this in some way. 

I'm erring towards not suggesting changes in the terminology -but thinking more about how to describe things better - but open to the alternative.

**Comment by dc-coder** [comment]
I agree on erring towards keeping things as is until there is a demonstrated need from multiple places. If multiple use cases show that extensions are becoming less useful because of random fields, then we can revisit. I think it would be good to just keep this issue at the "back of our minds"... because extensions might be the next big growth area of the standard... managing and having good extensions around specific themes is important and it is where community can contribute a lot.

Maybe a good thing to do is to add "local extension" to the documentation as a separate type and tweak the documentation a bit... then it is a bit more clear.

here is the current

![screen shot 2017-06-21 at 3 24 09 pm](https://user-images.githubusercontent.com/521705/27402754-bb7062ec-5695-11e7-82d0-2034e1fd6d8f.png)

here is the suggestion - is this too much? did i get this wrong? (suggested parts are in bold)

- Core extensions are documented as part of the standard and reviewed by the OCDS technical team with each version upgrade of OCDS. They are likely to be relevant to a large number of publishers and users.
- Community extension are maintained by third-parties, or are maintained outside of the standard governance process. They may provide features required by only a small number of publishers or users __and they address how to model one building block per extension. Community extensions are registered on [github](https://github.com/open-contracting/extension_registry), a list and description is part of the documentation.__  
- Local extension are maintained by third-parties, or are maintained outside of the standard governance process. __They may provide a schema for modeling country specific data that is not suitable for a community extension. Local extensions are not part of the data standard documentation and are not published on the Open Contracting GitHub.__

Does it make sense to say something along those lines in the documentation?

**Comment by jpmckinney** [comment]
Noting that this internal document may have some ideas to reuse here: https://docs.google.com/document/d/11ltDezD7aQPum2uEiPtMWXwXavdXSEvwLEwdvfISBM0/edit

**Comment by jpmckinney** [comment]
Moving to https://github.com/open-contracting/standard/issues/634
