### ISSUE TITLE
Why is milestone_documents core for v1.1, but not master

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/extension_registry#46]

**Comment by timgdavies** [comment]
This is a bug and should be updated.

**Comment by timgdavies** [comment]
@Bjwebb Could you make that change so that milestone_documents *is* core in master.

**Comment by Bjwebb** [comment]
I've run into this whilst looking at rebasing https://github.com/open-contracting/extension_registry/pull/45#issuecomment-310638982 onto v1.1, so I might wait until that PR is ready, and I actually do that, to check whether there's any similar cases.

**Comment by timgdavies** [comment]
Perfect.

**Comment by Bjwebb** [comment]
Looks like we're not backporting those changes, so I've just checked what `"core"` discrepancies there are between `master` and `v1.1`. `milestone_documents` is the only one.

**Comment by Bjwebb** [comment]
Pull request to make it core on master https://github.com/open-contracting/extension_registry/pull/48

**Comment by jpmckinney** [comment]
#48 is merged. Is this therefore closed?
