### ISSUE TITLE
Allow multiple versions of extensions in entry.json

### ISSUE THREAD

**Issue by kindly** [open-contracting/extension_registry#47]
In an entry.json file we should be able to specify multiple versions of extension.

An option on how this can be done is to allow the entry.json file to contain a list of different entry objects. The first in the list could be considered the latest one but each entry can contain its own semver and a list of versions of the standard its compatible with.
i.e

```
[
{"name": "bids",
 "version": "3",
 "url" : "http://some.urlr.2/extension.json",
 "compatibility": ["1.2"]
  .....
},
{"name": "bids",
 "version": "2.1",
 "url" : "http://some.urlr.2.1/extension.json",
 "compatibility": ["1.1"]
  .....
}
]

**Comment by jpmckinney** [comment]
We seem to have `1.1` in some entries' `category` (like [Budget breakdown](https://github.com/open-contracting/extension_registry/blob/master/budget_breakdown/entry.json#L14), though curiously the category list is comma-separated instead of using an array). I don't know the semantics/implications of that `1.1`, but if it's intended to indicate compatibility, it may be worth breaking out.

**Comment by timgdavies** [comment]
I believe the 1.1 in a category was to indicate it was something we were working on as part of 1.1 upgrade, not something about the compatibility of the extension. 

We should clean up the extension registry to remove those 1.1 tags.

**Comment by jpmckinney** [comment]
I just noticed that `extension.json` has `compatibility` (like for [Budget breakdown](https://raw.githubusercontent.com/open-contracting/ocds_budget_breakdown_extension/master/extension.json)). I don't know if this issue is about copying that over into the registry.

**Comment by jpmckinney** [comment]
This commit https://github.com/open-contracting/extension_registry/commit/227d43199bf615205ed2f059fea197d8e78e730a changed entry.json to an array, so I think this issue is closed. (Though, compile.py only takes the first entry.)
