### ISSUE TITLE
What are the semantics of `active`?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/extension_registry#52]
Can an extension go from inactive to active, or do extensions only ever get permanently 'retired' by being rendered inactive? Basically, in what cases would an extension be inactive?

**Comment by jpmckinney** [comment]
Noting that on today's call, we described `active` as an internal flag (e.g. to prevent a test extension in the registry from appearing on the website). That is, it is not a normative flag (which I had implied in the issue description).

That said, the field could use better documentation in the readme.

**Comment by jpmckinney** [comment]
Related #59

**Comment by edugomez** [comment]
> active as an internal flag (e.g. to prevent a test extension in the registry from appearing on the website)

@jpmckinney as you pointed out here #59 The only extension ```"active": false``` is https://github.com/open-contracting/ocds_documentation_extension. It shows in the standard documentation. 

However I don't see anywhere (https://github.com/open-contracting/ocds_sphinx_directives/blob/master/ocds_sphinx_directives.py , https://github.com/open-contracting/standard/blob/1.1-dev/standard/docs/en/_static/extensions.js) a check for active status.

**Comment by jpmckinney** [comment]
So, can we then remove the field from all `entry.json` files and from the schema for those files?

**Comment by edugomez** [comment]
I think we should. To be honest, don't see much point on having a 'testing' flag for an entry in the registry.

I just grepped most (all?) OCP repos locally and don't see this ```"active"``` use anywhere, so I'll go ahead.
