### ISSUE TITLE
.travis.yml lacks ltfp package

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/extension_registry#60]
The standard (and ppp) repo has:

```
addons:
  apt:
    packages:
    - lftp
```

Because its [deploy script](https://github.com/OpenDataServices/opendataservices-deploy/blob/master/open-contracting-standard-deploy.sh) uses ltfp.

However, this repo doesn't have that block in `.travis.yml`, despite using lftp in its [deploy script](https://github.com/OpenDataServices/opendataservices-deploy/blob/master/open-contracting-extension_registry-deploy.sh).

I think we should add that block for consistency. It's curious that deployment works – Travis doesn't list `lftp` as a default package.

**Comment by Bjwebb** [comment]
The deploy script will download a copy of lftp if it doesn't exist - https://github.com/OpenDataServices/opendataservices-deploy/blob/master/open-contracting-extension_registry-deploy.sh#L12

Installing via travis is better though (more explicit, less likely to break).
