### ISSUE TITLE
Metrics extension - tracking metrics across stages

### ISSUE THREAD

**Issue by dc-coder** [open-contracting/extension_registry#64]
> The metrics extension supports publication of forecasts (planning stage), targets (tender stage), agreed performance targets (award and contract stage) and results (implementation stage).

After reading the README on https://github.com/open-contracting/ocds_metrics_extension, here is what I gathered I should do if i was to model the monthly physical and financial progress agreed upon:

At the planning stage, data must be as follow

```json
{
  "forecasts": [
    {
      "id": "completionPercent",
      "title": "Construction progress (percent)",
      "description": "Percent completion of the construction",
      "observations": [
        {
          "period": {
            "startDate": "2017-01-01T00:00:00Z",
            "endDate": "2017-02-31T23:59:59Z"
          },
          "measure": "25",
          "unit": {
            "name": "percent",
            "id": "P1",
            "scheme": "UNCEFACT"
          }
        },
        {
          "period": {
            "startDate": "2017-02-01T00:00:00Z",
            "endDate": "2017-03-31T23:59:59Z"
          },
          "measure": "30",
          "unit": {
            "name": "percent",
            "id": "P1",
            "scheme": "UNCEFACT"
          }
        }
      ]
    }
  ]
}

```

at the tender, award and contract stage, the key  "forecasts" **must** become "targets"

at the implementation stage, it becomes metrics

```json
{
  "metrics": [
    {
      "id": "completionPercent",
      "title": "Construction progress (percent)",
      "description": "Percent completion of the construction",
      "observations": [
        {
          "period": {
            "startDate": "2017-01-01T00:00:00Z",
            "endDate": "2017-02-31T23:59:59Z"
          },
          "measure": "15",
          "unit": {
            "name": "percent",
            "id": "P1",
            "scheme": "UNCEFACT"
          }
        },
        {
          "period": {
            "startDate": "2017-02-01T00:00:00Z",
            "endDate": "2017-03-31T23:59:59Z"
          },
          "measure": "20",
          "unit": {
            "name": "percent",
            "id": "P1",
            "scheme": "UNCEFACT"
          }
        }
      ]
    }
  ]
}

```

When doing reporting or analytics, I can use the same ID , in this case "completionPercent" to track how well things unfolded at each of the stages.

So my questions are:
- is my assumption correct about the key name changing across the stages? at planning, key is "forecasts" , at implementation it is "metrics", in the rest of the stages it is "targets" 

- is this the best or recommended way to model the data? is there a way to avoid repeating the "unit" block for example?

**Comment by jpmckinney** [comment]
In `Award` and `Contract` objects, the field name is `agreedMetrics`. The others are correct: https://github.com/open-contracting/ocds_metrics_extension/blob/master/release-schema.json

The `unit` must be repeated, sadly.

**Comment by dc-coder** [comment]
thank you for clarification :) closing issue :)
