### ISSUE TITLE
Dependency of bids extension on requirements extension

### ISSUE THREAD

**Issue by julijahansen** [open-contracting/extension_registry#74]
At the moment if you want to use bids extension (https://github.com/open-contracting/ocds_bid_extension) you also need to declare requirements extension (https://github.com/open-contracting/ocds_requirements_extension), however this dependency appears to be a bug and should be removed.

**Comment by jpmckinney** [comment]
Noting related issue in CoVE https://github.com/OpenDataServices/cove/issues/823#issuecomment-326273195

**Comment by jpmckinney** [comment]
I think the solution is to remove https://github.com/open-contracting/ocds_bid_extension/blob/master/release-schema.json#L175-L183 and to add `title` and `description` to https://github.com/open-contracting/ocds_requirements_extension/blob/master/release-schema.json#L243-L249

**Comment by jpmckinney** [comment]
This issue should probably be in https://github.com/open-contracting/ocds-extensions but no worries, we'll close it here.

**Comment by jpmckinney** [comment]
I created the two PRs.
