### ISSUE TITLE
.travis.yml deploy configuration means PRs get deployed to production

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/extension_registry#75]
I assume we don't want all PR branches to get deployed…

**Comment by Bjwebb** [comment]
Branches don't clobber each other, branches get deployed to http://standard.open-contracting.org/extension_registry/{branch_name}/extensions.json

We want this to have a branch for a particular version of the standard, e.g. v1.1.1 branch at http://standard.open-contracting.org/extension_registry/v1.1.1/extensions.json

I don't think we particularly want this for all PR branches, but we'd need some way to separate the two types of branches. It might also be useful for people to preview the built json before it gets merged.

**Comment by jpmckinney** [comment]
I know they don't clobber - but it's not desirable to have everything automatically uploaded to the server. What if we just changed:

```
  on:
    all_branches: true
```

To be explicit about which branches to deploy?

**Comment by jpmckinney** [comment]
The documentation is not a simple build like the extension registry, so it makes sense to offer that preview functionality. With the registry, I don't know that anyone has ever previewed their PR in that way, and at any rate a preview is literally running compile.py, which anyone making changes to this repo should be capable of doing locally.

**Comment by jpmckinney** [comment]
https://docs.travis-ci.com/user/deployment/script

**Comment by jpmckinney** [comment]
https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A
