### ISSUE TITLE
Split extensions.csv into extension_versions.csv

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/extension_registry#95]
From #90:

@jpmckinney

> The new extensions.csv works for repositories whose releases (versions) can be determined via the version control system. However, extensions are allowed to be uploaded to e.g. an FTP server (imagine a folder of ZIP files for `extensionA.1.0.zip`, `extensionA.1.1.zip`, `extensionB.1.1.zip`, etc.) One solution is for each row of the CSV to be a release, rather than an extension; the URL would have to point to the specific release, and a Version column would have to be added for the version number. This would cause repetition of Id, Category, and Core across releases of a single extension. To address that, we can either add a consistency test, or have Id, Category and Core in one file, and Id, URL and Version in another file. The first file would be managed by standard authors who decide the Category and Core, whereas the management of the second file could be more distributed, as it will pretty much only be appended to via PR by extension authors.

> The new output files have columns for each release of the standard for which there are extensions released. While core extensions follow the standard's versioning, community extensions can use any version numbers they like. They can have a 1.1.3-alpha, 1.1.3-rc.1, 5.3, 11 – anything, really. So, we may need to, as above, have one release per row. This will duplicate some information, but as this file is generated, that duplication won't come with data integrity risks.

@odscjames 

> I would favour the second file approach - have a “extensionversions.csv” with columns like Id, Version, Reference.

> I think the problem you identify of repetition is an important one to avoid. Also this way, the number of columns that might not be relevant is reduced which makes for files that are easier to edit. And as you note, different people will tend to be editing different files so that cuts down on possible conflicts.

**Comment by odscjames** [comment]
Noted this is referenced in #85 to - ticked off item there as this is now dealt with here.
