### ISSUE TITLE
Add contactPoint to extensions data

### ISSUE THREAD

**Issue by odscjames** [open-contracting/extension_registry#97]
This spun off from #85

- [ ] Add to https://github.com/open-contracting/standard_extension_template/blob/master/extension.json and the appropriate JSON Schema. (This way extension authors can edit these values themselves - changes probably don't require approval.) 
- [ ] Change compile scripts in this repository to read values and add them to generated output.
- [ ] Update documentation on creating new extensions

Should the format allow multiple authors, something like:
```

{
	"authors": [{
			"name": "James",
			"email": "james@example.com "
		},
		{
			"name": "Bob",
			"email": "bob@example.com"
		}
	]
}

```

Fields fully optional so existing extensions aren't suddenly marked as broken.  Also do we want to support people giving a name but no email?

**Comment by jpmckinney** [comment]
I prefer a single point of contact, as otherwise people may contact one and not another, leading to confusion, etc. We could have, e.g.:

```json
{
  "contactPoint": {
    "name": "J",
    "email": "j@example.com"
  }
}
```

**Comment by jpmckinney** [comment]
Noting that this issue likely belongs on https://github.com/open-contracting/ocds-extensions/issues, as the contact information is anticipated to be added to each extension, rather than centrally controlled by the registry.

**Comment by jpmckinney** [comment]
Moved to https://github.com/open-contracting/ocds-extensions/issues/78
